version: '3'
volumes:
  mysql_data:
  public_data:
  tmp_data:
  log_data:
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/campgears
      - public_data:/campgears/public
      - tmp_data:/campgears/tmp
      - log_data:/campgears/log
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes:
      - public_data:/campgears/public
      - tmp_data:/campgears/tmp
    depends_on:
      - web